<?php

// Roughly 250 quotes spanning reading, education, learning, motivation,
// life, love, self-love, and scripture — shown on the Student/Teacher
// dashboard whenever there are no active announcements. See
// App\View\Components\QuoteOfTheDay for how one is picked per user per day.
return [
    'A room without books is like a body without a soul.',
    'Today a reader, tomorrow a leader.',
    'Reading is to the mind what exercise is to the body.',
    'There is no friend as loyal as a book.',
    'Once you learn to read, you will be forever free.',
    'Books are a uniquely portable magic.',
    'The more that you read, the more things you will know.',
    'Reading gives us someplace to go when we have to stay where we are.',
    'A book is a dream that you hold in your hand.',
    'Books are the quietest and most constant of friends.',
    'I find television very educating. Every time somebody turns it on, I go into another room and read a book.',
    'Reading is essential for those who seek to rise above the ordinary.',
    'A great book should leave you with many experiences, and slightly exhausted at the end.',
    'You can never get a cup of tea large enough or a book long enough to suit me.',
    'There are worse crimes than burning books. One of them is not reading them.',
    'Reading is a discount ticket to everywhere.',
    'When I look back, I am so impressed again with the life-giving power of literature.',
    'Books let us into their souls and lay open to us the secrets of our own.',
    'A book is a gift you can open again and again.',
    'The reading of all good books is like conversation with the finest men of past centuries.',
    'Read the best books first, or you may not have a chance to read them at all.',
    'Never trust anyone who has not brought a book with them.',
    'Sleep is good, and books are better.',
    'There is more treasure in books than in all the pirate\'s loot on Treasure Island.',
    'Books are lighthouses erected in the sea of time.',
    'Reading brings us unknown friends.',
    'Books serve to show a man that those original thoughts of his aren\'t very new after all.',
    'A book is the only place in which you can examine a fragile thought without breaking it.',
    'Words can be like X-rays if you use them properly, they will go through anything.',
    'Outside of a dog, a book is man\'s best friend. Inside of a dog it\'s too dark to read.',
    'Books are mirrors: you only see in them what you already have inside you.',
    'Reading is an act of civilization; it\'s one of the greatest acts of civilization there is.',
    'There is no such thing as a moral or immoral book; books are well written or badly written.',
    'A little library, growing larger every year, is an honorable part of a man\'s history.',
    'Libraries store the energy that fuels the imagination.',
    'Reading one book is like eating one potato chip.',
    'The person who deserves most pity is a lonesome one on a rainy day who doesn\'t know how to read.',
    'Books wash away from the soul the dust of everyday life.',
    'I do believe something very magical can happen when you read a good book.',
    'You know you\'ve read a good book when you turn the last page and feel a little as if you have lost a friend.',
    'Reading is the gateway that makes all other learning possible.',
    'Education is the most powerful weapon which you can use to change the world.',
    'The beautiful thing about learning is that no one can take it away from you.',
    'Education is the passport to the future, for tomorrow belongs to those who prepare for it today.',
    'An investment in knowledge pays the best interest.',
    'Education is not the filling of a pail, but the lighting of a fire.',
    'The whole purpose of education is to turn mirrors into windows.',
    'Live as if you were to die tomorrow. Learn as if you were to live forever.',
    'Education breeds confidence. Confidence breeds hope. Hope breeds peace.',
    'The roots of education are bitter, but the fruit is sweet.',
    'Develop a passion for learning. If you do, you will never cease to grow.',
    'Learning never exhausts the mind.',
    'Education is what remains after one has forgotten everything learned in school.',
    'Change is the end result of all true learning.',
    'The mind is not a vessel to be filled but a fire to be kindled.',
    'Anyone who stops learning is old, whether at twenty or eighty.',
    'Education\'s purpose is to replace an empty mind with an open one.',
    'Learning is a treasure that will follow its owner everywhere.',
    'Wisdom is not a product of schooling but of the lifelong attempt to acquire it.',
    'Knowledge is power. Information is liberating.',
    'Study hard what interests you the most in the most undisciplined, irreverent way possible.',
    'Education is our passport to the future.',
    'The function of education is to teach one to think intensively and to think critically.',
    'Real education should educate us out of self into something far finer.',
    'It is the mark of an educated mind to be able to entertain a thought without accepting it.',
    'Education is not preparation for life; education is life itself.',
    'Intelligence plus character, that is the goal of true education.',
    'Formal education will make you a living; self-education will make you a fortune.',
    'The beautiful thing about learning is nobody can take it away from you.',
    'Every act of learning allows a person to become a little more.',
    'You are never too old to set another goal or to dream a new dream.',
    'Learning never exhausts the mind; it only fuels curiosity.',
    'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.',
    'Curiosity is the wick in the candle of learning.',
    'What we learn with pleasure we never forget.',
    'Learning is not attained by chance, it must be sought for with ardor and diligence.',
    'Mistakes are proof that you are trying and learning.',
    'Learning is a lifelong journey, not a destination.',
    'The expert in anything was once a beginner.',
    'Every day is a chance to learn something new.',
    'To learn is to grow; to stop learning is to stop living fully.',
    'Skill comes from consistent practice, not talent alone.',
    'Learning never stops; every experience teaches something new.',
    'The more you learn, the more places you\'ll go.',
    'An investment in learning always pays the best dividends.',
    'Learning is the only thing the mind never exhausts, never fears, and never regrets.',
    'You don\'t learn to walk by following rules. You learn by doing and falling over.',
    'Believe you can and you\'re halfway there.',
    'The future belongs to those who believe in the beauty of their dreams.',
    'It always seems impossible until it\'s done.',
    'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    'Hardships often prepare ordinary people for an extraordinary destiny.',
    'Don\'t watch the clock; do what it does. Keep going.',
    'The only way to do great work is to love what you do.',
    'Your limitation, it\'s only your imagination.',
    'Push yourself, because no one else is going to do it for you.',
    'Great things never come from comfort zones.',
    'Dream it. Wish it. Do it.',
    'Success doesn\'t just find you. You have to go out and get it.',
    'The harder you work for something, the greater you\'ll feel when you achieve it.',
    'Don\'t stop when you\'re tired. Stop when you\'re done.',
    'Wake up with determination. Go to bed with satisfaction.',
    'Little things make big days.',
    'It\'s going to be hard, but hard does not mean impossible.',
    'Don\'t wait for opportunity. Create it.',
    'Sometimes we\'re tested not to show our weaknesses, but to discover our strengths.',
    'The key to success is to focus on goals, not obstacles.',
    'Dream bigger. Do bigger.',
    'Don\'t be afraid to give up the good to go for the great.',
    'Success is the sum of small efforts repeated day in and day out.',
    'Difficult roads often lead to beautiful destinations.',
    'Believe in yourself and all that you are.',
    'You don\'t have to be great to start, but you have to start to be great.',
    'Opportunities don\'t happen. You create them.',
    'The secret of getting ahead is getting started.',
    'A year from now you may wish you had started today.',
    'Doubt kills more dreams than failure ever will.',
    'Everything you\'ve ever wanted is on the other side of fear.',
    'Start where you are. Use what you have. Do what you can.',
    'The only limit to our realization of tomorrow is our doubts of today.',
    'Act as if what you do makes a difference. It does.',
    'You are capable of more than you know.',
    'Discipline is the bridge between goals and accomplishment.',
    'Small steps every day lead to big results over time.',
    'Your only limit is you.',
    'Progress, not perfection.',
    'Keep going. Everything you need will come to you at the perfect time.',
    'What you get by achieving your goals is not as important as what you become by achieving your goals.',
    'The way to get started is to quit talking and begin doing.',
    'If you want to lift yourself up, lift up someone else.',
    'Nothing is impossible; the word itself says I\'m possible.',
    'Try to be a rainbow in someone\'s cloud.',
    'You are stronger than you think.',
    'Perseverance is not a long race; it is many short races one after the other.',
    'Fall seven times, stand up eight.',
    'Don\'t limit your challenges, challenge your limits.',
    'Life is what happens when you\'re busy making other plans.',
    'In the end, it\'s not the years in your life that count. It\'s the life in your years.',
    'Life is either a daring adventure or nothing at all.',
    'The purpose of our lives is to be happy.',
    'Get busy living or get busy dying.',
    'You only live once, but if you do it right, once is enough.',
    'Many of life\'s failures are people who did not realize how close they were to success when they gave up.',
    'Life is really simple, but we insist on making it complicated.',
    'The good life is one inspired by love and guided by knowledge.',
    'Life is a succession of lessons which must be lived to be understood.',
    'Turn your wounds into wisdom.',
    'Life shrinks or expands in proportion to one\'s courage.',
    'Not how long, but how well you have lived is the main thing.',
    'The unexamined life is not worth living.',
    'Life is 10% what happens to us and 90% how we react to it.',
    'To live is the rarest thing in the world. Most people exist, that is all.',
    'Life is short, and it is up to you to make it sweet.',
    'Every moment is a fresh beginning.',
    'Yesterday is history, tomorrow is a mystery, today is a gift.',
    'Enjoy the little things, for one day you may look back and realize they were the big things.',
    'Be yourself; everyone else is already taken.',
    'Life is like riding a bicycle. To keep your balance, you must keep moving.',
    'The best way to predict your future is to create it.',
    'Do not wait for the perfect moment. Take the moment and make it perfect.',
    'You can\'t go back and change the beginning, but you can start where you are and change the ending.',
    'Everything has beauty, but not everyone sees it.',
    'Life is a journey, not a destination.',
    'In three words I can sum up everything I\'ve learned about life: it goes on.',
    'The purpose of life is a life of purpose.',
    'Life isn\'t about finding yourself. It\'s about creating yourself.',
    'The two most important days in your life are the day you are born and the day you find out why.',
    'Where there is love there is life.',
    'Love is composed of a single soul inhabiting two bodies.',
    'The best thing to hold onto in life is each other.',
    'Love recognizes no barriers.',
    'To love and be loved is to feel the sun from both sides.',
    'Love is not about how much you say I love you, but how much you prove it\'s true.',
    'We are shaped and fashioned by what we love.',
    'Love yourself first and everything else falls into line.',
    'Love all, trust a few, do wrong to none.',
    'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.',
    'A loving heart is the truest wisdom.',
    'Love is a friendship set to music.',
    'The greatest happiness of life is the conviction that we are loved.',
    'Love is an untamed force. When we try to control it, it destroys us.',
    'Where love resides, the imperfections are made perfect.',
    'In all the world, there is no heart for me like yours.',
    'Love takes off masks that we fear we cannot live without and know we cannot live within.',
    'Life is the flower for which love is the honey.',
    'There is only one happiness in life: to love and be loved.',
    'Love yourself, forgive yourself, and be good to yourself.',
    'Love is patient, love is kind.',
    'The heart that loves is always young.',
    'Love is a friendship caught fire.',
    'Self-love is not selfish; you cannot truly love another until you know how to love yourself.',
    'You yourself, as much as anybody in the entire universe, deserve your love and affection.',
    'To love oneself is the beginning of a lifelong romance.',
    'Talk to yourself like you would to someone you love.',
    'You are allowed to be both a masterpiece and a work in progress.',
    'Owning our story and loving ourselves through that process is the bravest thing we\'ll ever do.',
    'Self-care is how you take your power back.',
    'You are enough just as you are.',
    'Be kind to yourself. You are doing the best you can.',
    'Your relationship with yourself sets the tone for every other relationship.',
    'You don\'t have to be perfect to be worthy of love.',
    'Self-love is recognizing that you are your own soulmate.',
    'Fill your own cup first, then pour into others.',
    'Rest is not a reward for finishing; it is a requirement for continuing.',
    'Growth is a process, and every step you take matters, even the small ones.',
    'You are worthy of the love you keep giving to everyone else.',
    'Healing takes time, and asking for help is a courageous step.',
    'Choosing yourself is not selfish; it\'s necessary.',
    'Give yourself permission to rest and just be, not just do.',
    'Your value doesn\'t decrease based on someone\'s inability to see your worth.',
    'Almost everything will work again if you unplug it for a few minutes, including you.',
    'You are your own best investment.',
    'Take care of your body. It\'s the only place you have to live.',
    'I can do all things through Christ who strengthens me. Philippians 4:13',
    'Trust in the Lord with all your heart and lean not on your own understanding. Proverbs 3:5',
    'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you. Jeremiah 29:11',
    'Be strong and courageous. Do not be afraid; do not be discouraged. Joshua 1:9',
    'The Lord is my shepherd, I lack nothing. Psalm 23:1',
    'Cast all your anxiety on him because he cares for you. 1 Peter 5:7',
    'But those who hope in the Lord will renew their strength. They will soar on wings like eagles. Isaiah 40:31',
    'And we know that in all things God works for the good of those who love him. Romans 8:28',
    'Come to me, all you who are weary and burdened, and I will give you rest. Matthew 11:28',
    'Delight yourself in the Lord, and he will give you the desires of your heart. Psalm 37:4',
    'Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God. Philippians 4:6',
    'The Lord is close to the brokenhearted and saves those who are crushed in spirit. Psalm 34:18',
    'Above all else, guard your heart, for everything you do flows from it. Proverbs 4:23',
    'She is clothed with strength and dignity; she can laugh at the days to come. Proverbs 31:25',
    'Let all that you do be done in love. 1 Corinthians 16:14',
    'For God has not given us a spirit of fear, but of power, and of love, and of a sound mind. 2 Timothy 1:7',
    'This is the day that the Lord has made; let us rejoice and be glad in it. Psalm 118:24',
    'Commit to the Lord whatever you do, and he will establish your plans. Proverbs 16:3',
    'Give thanks in all circumstances; for this is God\'s will for you. 1 Thessalonians 5:18',
    'He heals the brokenhearted and binds up their wounds. Psalm 147:3',
    'Rejoice in hope, be patient in tribulation, be constant in prayer. Romans 12:12',
    'Let us not become weary in doing good, for at the proper time we will reap a harvest. Galatians 6:9',
    'Be joyful in hope, patient in affliction, faithful in prayer. Romans 12:12',
    'The joy of the Lord is your strength. Nehemiah 8:10',
    'Whatever you do, work at it with all your heart, as working for the Lord. Colossians 3:23',
];
